import 'dart:convert';
import 'dart:math' as math;
import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import '../../../../core/services/web_speech/web_speech.dart';
import '../../../../core/services/mind_map_synthesizer.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_text_styles.dart';
import '../../../../core/theme/app_neumorphic.dart';
import '../../../../shared_models/notes.dart';
import '../controllers/notes_quiz_controller.dart';

class MindMapTab extends ConsumerStatefulWidget {
  const MindMapTab({super.key});

  @override
  ConsumerState<MindMapTab> createState() => _MindMapTabState();
}

class _MindMapTabState extends ConsumerState<MindMapTab> {
  final GlobalKey _boundaryKey = GlobalKey();
  bool _isExporting = false;

  Future<void> _exportMindMapImage({required String format, bool isShare = false}) async {
    if (_isExporting) return;
    setState(() => _isExporting = true);

    try {
      final boundary =
          _boundaryKey.currentContext?.findRenderObject() as RenderRepaintBoundary?;
      if (boundary == null) {
        throw Exception('Could not locate mind map canvas.');
      }

      // Capture crisp high-res raster
      final image = await boundary.toImage(pixelRatio: 3.0);
      final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      if (byteData == null) {
        throw Exception('Could not encode canvas into image bytes.');
      }

      final imgBytes = byteData.buffer.asUint8List();
      final lecture = ref.read(notesQuizControllerProvider).lecture;
      final lectureTitle = lecture?.title ?? 'MindMap';
      final cleanTitle =
          lectureTitle.replaceAll(RegExp(r'[^\w\s]+'), '').replaceAll(' ', '_');
      final fileName = 'MindMap_$cleanTitle.$format';
      final mimeType = format == 'jpg' ? 'image/jpeg' : 'image/png';

      if (kIsWeb && !isShare) {
        final base64Data = base64Encode(imgBytes);
        final downloaded = WebSpeechBridge.downloadImage(
          base64Data: base64Data,
          filename: fileName,
          mimeType: mimeType,
        );
        if (!downloaded) {
          await Printing.sharePdf(bytes: imgBytes, filename: fileName);
        }
      } else {
        await Share.shareXFiles(
          [
            XFile.fromData(
              imgBytes,
              name: fileName,
              mimeType: mimeType,
            ),
          ],
          text: 'Concept Mind Map: $lectureTitle\nGenerated by LectureMind AI',
        );
      }

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Mind Map image successfully exported ($fileName)!'),
            backgroundColor: AppColors.sabaqGreen,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to export mind map: $e'),
            backgroundColor: AppColors.error,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isExporting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final state = ref.watch(notesQuizControllerProvider);
    final lecture = state.lecture;
    final scheme = Theme.of(context).colorScheme;
    final isDark = Theme.of(context).brightness == Brightness.dark;

    if (lecture == null) {
      return const Center(child: Text('No mind map available.'));
    }

    // Always guarantee a rich multi-tier knowledge graph covering 100% of speech
    final rawNodes = (lecture.mindMapNodes.isNotEmpty && lecture.mindMapNodes.length >= 8)
        ? lecture.mindMapNodes
        : MindMapSynthesizer.synthesizeNodes(
            title: lecture.title,
            transcript: lecture.sections
                .map((s) => '${s.title}. ${s.body} ${s.bullets.join(". ")}')
                .join(' '),
            sections: lecture.sections,
          );

    return Column(
      children: [
        // ── Top Toolbar with Direct PNG / JPG Export & Share ──────────────────
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          decoration: BoxDecoration(
            color: isDark ? NeuColors.darkSurface : NeuColors.lightSurface,
            boxShadow: [
              BoxShadow(
                color: isDark ? NeuColors.darkDarkShadow : NeuColors.lightDarkShadow,
                blurRadius: 10,
                offset: const Offset(0, 4),
              ),
            ],
          ),
          child: Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Multi-Tier Conceptual Knowledge Graph',
                      style: AppTextStyles.bodyStrong(scheme.onSurface)
                          .copyWith(fontSize: 13.5, fontWeight: FontWeight.w700),
                    ),
                    const SizedBox(height: 3),
                    Row(
                      children: [
                        Text(
                          '${rawNodes.length} nodes',
                          style: AppTextStyles.caption(scheme.onSurfaceVariant),
                        ),
                        const SizedBox(width: 8),
                        Container(width: 7, height: 7, decoration: const BoxDecoration(color: AppColors.crimsonRed, shape: BoxShape.circle)),
                        const SizedBox(width: 4),
                        Text('Core & Pillars', style: AppTextStyles.caption(scheme.onSurfaceVariant).copyWith(fontSize: 11)),
                        const SizedBox(width: 10),
                        Container(width: 7, height: 7, decoration: const BoxDecoration(color: Color(0xFF2563EB), shape: BoxShape.circle)),
                        const SizedBox(width: 4),
                        Text('Concepts & Facts', style: AppTextStyles.caption(scheme.onSurfaceVariant).copyWith(fontSize: 11)),
                        const SizedBox(width: 10),
                        Container(width: 7, height: 7, decoration: const BoxDecoration(color: Color(0xFFF59E0B), shape: BoxShape.circle)),
                        const SizedBox(width: 4),
                        Text('Domain Expansion', style: AppTextStyles.caption(const Color(0xFFD97706)).copyWith(fontSize: 11, fontWeight: FontWeight.w700)),
                      ],
                    ),
                  ],
                ),
              ),
              // PNG Download
              SizedBox(
                height: 38,
                child: NeuButton(
                  label: 'PNG',
                  icon: Icons.download_rounded,
                  isPrimary: false,
                  height: 38,
                  radius: 19,
                  onPressed: _isExporting ? null : () => _exportMindMapImage(format: 'png'),
                ),
              ),
              const SizedBox(width: 8),
              // JPG Download — Main Feature Highlighted
              SizedBox(
                height: 38,
                child: NeuButton(
                  label: 'Download JPG',
                  icon: Icons.image_rounded,
                  isPrimary: true,
                  height: 38,
                  radius: 19,
                  onPressed: _isExporting ? null : () => _exportMindMapImage(format: 'jpg'),
                ),
              ),
              const SizedBox(width: 8),
              // Share button
              NeuIconButton(
                icon: Icons.share_rounded,
                tooltip: 'Share Mind Map',
                onPressed: _isExporting
                    ? null
                    : () => _exportMindMapImage(format: 'png', isShare: true),
              ),
            ],
          ),
        ),

        // ── Interactive Aligned Canvas ───────────────────────────────────────
        Expanded(
          child: InteractiveViewer(
            minScale: 0.2,
            maxScale: 4.5,
            boundaryMargin: const EdgeInsets.all(500),
            child: Center(
              child: RepaintBoundary(
                key: _boundaryKey,
                child: Container(
                  width: 2500,
                  height: 1900,
                  color: isDark ? NeuColors.darkCanvas : NeuColors.lightCanvas,
                  child: CustomPaint(
                    painter: _HierarchicalMindMapPainter(
                      nodes: rawNodes,
                      isDark: isDark,
                      lectureTitle: lecture.title,
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ],
    );
  }
}

class _HierarchicalMindMapPainter extends CustomPainter {
  _HierarchicalMindMapPainter({
    required this.nodes,
    required this.isDark,
    required this.lectureTitle,
  });

  final List<MindMapNode> nodes;
  final bool isDark;
  final String lectureTitle;

  static const List<Color> _palette = [
    Color(0xFFE50914), // Crimson
    Color(0xFF2563EB), // Royal Blue
    Color(0xFF059669), // Emerald Green
    Color(0xFFD97706), // Amber
    Color(0xFF7C3AED), // Violet
    Color(0xFF0891B2), // Cyan
    Color(0xFFDB2777), // Pink
  ];

  @override
  void paint(Canvas canvas, Size size) {
    final center = Offset(size.width / 2, size.height / 2);

    // 1. Draw subtle blueprint dot grid
    final dotPaint = Paint()
      ..color = (isDark ? Colors.white : Colors.black).withValues(alpha: 0.05);
    for (double x = 40; x < size.width; x += 40) {
      for (double y = 40; y < size.height; y += 40) {
        canvas.drawCircle(Offset(x, y), 1.2, dotPaint);
      }
    }

    // 2. Identify root node
    final root = nodes.firstWhere(
      (n) =>
          n.id == 'root' ||
          n.id == 'center' ||
          n.parentId == null ||
          n.parentId!.isEmpty,
      orElse: () => MindMapNode(id: 'root', label: lectureTitle, tier: 0),
    );

    // 3. Identify Tier 1 pillars (direct children of root, excluding expansions)
    final pillars = nodes.where((n) {
      if (n.id == root.id) return false;
      if (n.isExpansion) return false;
      return n.parentId == root.id ||
          n.parentId == 'center' ||
          n.parentId == null ||
          n.tier == 1;
    }).toList();

    // Expansion nodes (attached to root)
    final expansions = nodes.where((n) => n.isExpansion).toList();

    // Map each pillar ID to an assigned theme color
    final Map<String, Color> pillarColors = {};
    for (int i = 0; i < pillars.length; i++) {
      pillarColors[pillars[i].id] = _palette[i % _palette.length];
    }

    final Map<String, Offset> nodePositions = {root.id: center};
    const double pillarRadius = 350.0;
    const double subRadius = 600.0;
    const double leafRadius = 840.0;

    final int numPillars = math.max(1, pillars.length);
    final double sectorAngle = (2 * math.pi) / numPillars;

    // 4. Calculate aligned positions & draw connections
    for (int i = 0; i < numPillars; i++) {
      final p = pillars[i];
      final pAngle = sectorAngle * i - (math.pi / 2);
      final pPos = Offset(
        center.dx + pillarRadius * math.cos(pAngle),
        center.dy + pillarRadius * math.sin(pAngle),
      );
      nodePositions[p.id] = pPos;

      final pColor = pillarColors[p.id] ?? AppColors.crimsonRed;

      // Draw curved line from Root to Pillar
      final rootEdgePaint = Paint()
        ..color = pColor.withValues(alpha: isDark ? 0.7 : 0.5)
        ..strokeWidth = 3.5
        ..style = PaintingStyle.stroke
        ..strokeCap = StrokeCap.round;

      final rootPath = Path()
        ..moveTo(center.dx, center.dy)
        ..quadraticBezierTo(
          (center.dx + pPos.dx) / 2 + (math.cos(pAngle + math.pi / 2) * 20),
          (center.dy + pPos.dy) / 2 + (math.sin(pAngle + math.pi / 2) * 20),
          pPos.dx,
          pPos.dy,
        );
      canvas.drawPath(rootPath, rootEdgePaint);

      // Find direct children of this pillar (Tier 2 sub-concepts)
      final subConcepts = nodes
          .where((n) => n.parentId == p.id && !n.isExpansion && n.id != root.id)
          .toList();

      final int sCount = subConcepts.length;
      final double subSpread = sectorAngle * 0.75;

      for (int j = 0; j < sCount; j++) {
        final sub = subConcepts[j];
        final subAngle = sCount == 1
            ? pAngle
            : (pAngle - subSpread / 2) + (subSpread / (sCount - 1)) * j;

        final subPos = Offset(
          center.dx + subRadius * math.cos(subAngle),
          center.dy + subRadius * math.sin(subAngle),
        );
        nodePositions[sub.id] = subPos;

        // Draw curved connection from Pillar to Sub-concept
        final subEdgePaint = Paint()
          ..color = pColor.withValues(alpha: isDark ? 0.5 : 0.35)
          ..strokeWidth = 2.4
          ..style = PaintingStyle.stroke
          ..strokeCap = StrokeCap.round;

        final subPath = Path()
          ..moveTo(pPos.dx, pPos.dy)
          ..quadraticBezierTo(
            (pPos.dx + subPos.dx) / 2,
            (pPos.dy + subPos.dy) / 2,
            subPos.dx,
            subPos.dy,
          );
        canvas.drawPath(subPath, subEdgePaint);

        // Find direct children of this sub-concept (Tier 3 detail leaves)
        final leaves = nodes.where((n) => n.parentId == sub.id).toList();
        final int lCount = leaves.length;

        for (int k = 0; k < lCount; k++) {
          final leaf = leaves[k];
          final leafAngle = lCount == 1
              ? subAngle
              : (subAngle - 0.15) + (0.3 / (lCount - 1)) * k;

          final leafPos = Offset(
            center.dx + leafRadius * math.cos(leafAngle),
            center.dy + leafRadius * math.sin(leafAngle),
          );
          nodePositions[leaf.id] = leafPos;

          // Draw fine connection from Sub-concept to Detail Leaf
          final leafEdgePaint = Paint()
            ..color = pColor.withValues(alpha: isDark ? 0.35 : 0.25)
            ..strokeWidth = 1.6
            ..style = PaintingStyle.stroke
            ..strokeCap = StrokeCap.round;

          final leafPath = Path()
            ..moveTo(subPos.dx, subPos.dy)
            ..quadraticBezierTo(
              (subPos.dx + leafPos.dx) / 2,
              (subPos.dy + leafPos.dy) / 2,
              leafPos.dx,
              leafPos.dy,
            );
          canvas.drawPath(leafPath, leafEdgePaint);
        }
      }
    }

    // 5. Position & connect Domain Expansions (Golden Amber)
    for (int eIdx = 0; eIdx < expansions.length; eIdx++) {
      final exp = expansions[eIdx];
      final expAngle = (sectorAngle * eIdx) + (sectorAngle / 2) - (math.pi / 2);
      const expRadius = 450.0;
      final expPos = Offset(
        center.dx + expRadius * math.cos(expAngle),
        center.dy + expRadius * math.sin(expAngle),
      );
      nodePositions[exp.id] = expPos;

      // Draw dashed golden edge to root
      final expPaint = Paint()
        ..color = const Color(0xFFF59E0B).withValues(alpha: isDark ? 0.6 : 0.45)
        ..strokeWidth = 2.0
        ..style = PaintingStyle.stroke;

      canvas.drawLine(center, expPos, expPaint);
    }

    // 6. Draw all nodes in proper z-order (leaves -> sub-concepts -> pillars -> expansions -> root)

    // A. Draw Tier 3 Detail Leaves
    for (final n in nodes.where((n) => n.tier == 3 || n.id.contains('_leaf') || n.id.contains('_detail'))) {
      if (nodePositions.containsKey(n.id)) {
        _drawNode(
          canvas,
          nodePositions[n.id]!,
          n.label,
          tier: 3,
          accentColor: const Color(0xFF2563EB),
          isExpansion: false,
        );
      }
    }

    // B. Draw Tier 2 Sub-concepts
    for (final n in nodes.where((n) => n.tier == 2 && !n.id.contains('_leaf') && !n.id.contains('_detail'))) {
      if (nodePositions.containsKey(n.id)) {
        _drawNode(
          canvas,
          nodePositions[n.id]!,
          n.label,
          tier: 2,
          accentColor: const Color(0xFF059669),
          isExpansion: false,
        );
      }
    }

    // C. Draw Tier 1 Pillars
    for (final p in pillars) {
      if (nodePositions.containsKey(p.id)) {
        final pColor = pillarColors[p.id] ?? AppColors.crimsonRed;
        _drawNode(
          canvas,
          nodePositions[p.id]!,
          p.label,
          tier: 1,
          accentColor: pColor,
          isExpansion: false,
        );
      }
    }

    // D. Draw Domain Expansions
    for (final exp in expansions) {
      if (nodePositions.containsKey(exp.id)) {
        _drawNode(
          canvas,
          nodePositions[exp.id]!,
          exp.label,
          tier: 1,
          accentColor: const Color(0xFFF59E0B),
          isExpansion: true,
        );
      }
    }

    // E. Draw Root Node on top
    _drawNode(
      canvas,
      center,
      root.label.isNotEmpty ? root.label : lectureTitle,
      tier: 0,
      accentColor: AppColors.crimsonRed,
    );
  }

  void _drawNode(
    Canvas canvas,
    Offset offset,
    String label, {
    required int tier,
    required Color accentColor,
    bool isExpansion = false,
  }) {
    final isRoot = tier == 0;
    final isPillar = tier == 1;
    final isLeaf = tier == 3;

    final double fontSize = isRoot ? 14 : (isPillar ? 12 : (isLeaf ? 9.5 : 10.5));
    final FontWeight fontWeight = isRoot
        ? FontWeight.w800
        : (isPillar ? FontWeight.w700 : (isLeaf ? FontWeight.w500 : FontWeight.w600));
    final double maxBoxWidth = isRoot ? 200 : (isPillar ? 160 : (isLeaf ? 135 : 145));
    final isUrdu = RegExp(r'[\u0600-\u06FF]').hasMatch(label);

    final textSpan = TextSpan(
      text: label,
      style: TextStyle(
        fontSize: fontSize,
        fontWeight: fontWeight,
        color: isRoot
            ? Colors.white
            : (isDark ? Colors.white : const Color(0xFF1E293B)),
      ),
    );

    final textPainter = TextPainter(
      text: textSpan,
      textDirection: isUrdu ? TextDirection.rtl : TextDirection.ltr,
      maxLines: 3,
      textAlign: TextAlign.center,
    )..layout(maxWidth: maxBoxWidth);

    final padH = isRoot ? 22.0 : (isPillar ? 16.0 : (isLeaf ? 10.0 : 12.0));
    final padV = isRoot ? 14.0 : (isPillar ? 10.0 : (isLeaf ? 6.0 : 8.0));

    final rect = Rect.fromCenter(
      center: offset,
      width: textPainter.width + padH * 2,
      height: textPainter.height + padV * 2,
    );
    final rrect = RRect.fromRectAndRadius(
      rect,
      Radius.circular(isRoot ? 18 : (isPillar ? 12 : (isLeaf ? 6 : 8))),
    );

    // Ambient drop shadow
    canvas.drawRRect(
      rrect.shift(const Offset(0, 4)),
      Paint()
        ..color = isRoot
            ? accentColor.withValues(alpha: 0.35)
            : (isExpansion
                ? const Color(0xFFF59E0B).withValues(alpha: 0.28)
                : Colors.black.withValues(alpha: isDark ? 0.3 : 0.08))
        ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 8),
    );

    // Node fill
    final fillPaint = Paint()
      ..color = isRoot
          ? accentColor
          : (isExpansion
              ? (isDark ? const Color(0xFF1E1E2E) : const Color(0xFFFFFBEB))
              : (isLeaf
                  ? (isDark ? const Color(0xFF182234) : const Color(0xFFF8FAFC))
                  : (isDark ? const Color(0xFF1E293B) : Colors.white)));
    canvas.drawRRect(rrect, fillPaint);

    // Node outline border
    final borderPaint = Paint()
      ..color = isRoot
          ? AppColors.deepCrimson
          : (isExpansion
              ? const Color(0xFFF59E0B)
              : (isPillar
                  ? accentColor
                  : (isLeaf
                      ? (isDark ? const Color(0xFF334155) : const Color(0xFFCBD5E1))
                      : (isDark ? const Color(0xFF334155) : const Color(0xFFE2E8F0)))))
      ..strokeWidth = isRoot ? 3.0 : (isExpansion ? 2.2 : (isPillar ? 2.0 : (isLeaf ? 1.0 : 1.4)))
      ..style = PaintingStyle.stroke;
    canvas.drawRRect(rrect, borderPaint);

    // Accent indicator pip on pillars and expansion nodes
    if (isPillar || isExpansion) {
      final pipPaint = Paint()..color = accentColor;
      canvas.drawCircle(Offset(rect.left + 10, rect.top + 10), 3.5, pipPaint);
    }

    // Paint text centered
    textPainter.paint(
      canvas,
      Offset(
        offset.dx - textPainter.width / 2,
        offset.dy - textPainter.height / 2,
      ),
    );
  }

  @override
  bool shouldRepaint(covariant _HierarchicalMindMapPainter oldDelegate) => true;
}
