import 'dart:convert';
import 'dart:math' as math;
import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import '../../../../core/services/web_speech/web_speech.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_text_styles.dart';
import '../../../../core/theme/app_neumorphic.dart';
import '../../../../shared_models/notes.dart';
import '../controllers/notes_quiz_controller.dart';

class MindMapTab extends ConsumerStatefulWidget {
  const MindMapTab({super.key});

  @override
  ConsumerState<MindMapTab> createState() => _MindMapTabState();
}

class _MindMapTabState extends ConsumerState<MindMapTab> {
  final GlobalKey _boundaryKey = GlobalKey();
  bool _isExporting = false;

  Future<void> _exportMindMapImage({required String format, bool isShare = false}) async {
    if (_isExporting) return;
    setState(() => _isExporting = true);

    try {
      final boundary =
          _boundaryKey.currentContext?.findRenderObject() as RenderRepaintBoundary?;
      if (boundary == null) {
        throw Exception('Could not locate mind map canvas.');
      }

      // Capture crisp high-res raster
      final image = await boundary.toImage(pixelRatio: 3.0);
      final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      if (byteData == null) {
        throw Exception('Could not encode canvas into image bytes.');
      }

      final imgBytes = byteData.buffer.asUint8List();
      final lecture = ref.read(notesQuizControllerProvider).lecture;
      final lectureTitle = lecture?.title ?? 'MindMap';
      final cleanTitle =
          lectureTitle.replaceAll(RegExp(r'[^\w\s]+'), '').replaceAll(' ', '_');
      final fileName = 'MindMap_$cleanTitle.$format';
      final mimeType = format == 'jpg' ? 'image/jpeg' : 'image/png';

      if (kIsWeb && !isShare) {
        final base64Data = base64Encode(imgBytes);
        final downloaded = WebSpeechBridge.downloadImage(
          base64Data: base64Data,
          filename: fileName,
          mimeType: mimeType,
        );
        if (!downloaded) {
          // Fallback
          await Printing.sharePdf(bytes: imgBytes, filename: fileName);
        }
      } else {
        await Share.shareXFiles(
          [
            XFile.fromData(
              imgBytes,
              name: fileName,
              mimeType: mimeType,
            ),
          ],
          text: 'Concept Mind Map: $lectureTitle\nGenerated by LectureMind AI',
        );
      }

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Mind Map image successfully exported ($fileName)!'),
            backgroundColor: AppColors.sabaqGreen,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to export mind map: $e'),
            backgroundColor: AppColors.error,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isExporting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final state = ref.watch(notesQuizControllerProvider);
    final lecture = state.lecture;
    final scheme = Theme.of(context).colorScheme;
    final isDark = Theme.of(context).brightness == Brightness.dark;

    if (lecture == null) {
      return const Center(child: Text('No mind map available.'));
    }

    final rawNodes = lecture.mindMapNodes.isNotEmpty
        ? lecture.mindMapNodes
        : [
            MindMapNode(id: 'root', label: lecture.title, tier: 0),
            for (int i = 0; i < lecture.sections.length; i++) ...[
              MindMapNode(
                id: 'sec_$i',
                label: lecture.sections[i].title,
                parentId: 'root',
                tier: 1,
              ),
              for (int j = 0; j < lecture.sections[i].bulletItems.length; j++)
                MindMapNode(
                  id: 'b_${i}_$j',
                  label: lecture.sections[i].bulletItems[j].point,
                  parentId: 'sec_$i',
                  tier: 2,
                ),
            ],
          ];

    return Column(
      children: [
        // ── Top Toolbar with Direct PNG / JPG Export & Share ──────────────────
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          decoration: BoxDecoration(
            color: isDark ? NeuColors.darkSurface : NeuColors.lightSurface,
            boxShadow: [
              BoxShadow(
                color: isDark ? NeuColors.darkDarkShadow : NeuColors.lightDarkShadow,
                blurRadius: 10,
                offset: const Offset(0, 4),
              ),
            ],
          ),
          child: Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Multi-Tier Conceptual Knowledge Graph',
                      style: AppTextStyles.bodyStrong(scheme.onSurface)
                          .copyWith(fontSize: 13.5, fontWeight: FontWeight.w700),
                    ),
                    const SizedBox(height: 3),
                    Row(
                      children: [
                        Text(
                          '${rawNodes.length} nodes',
                          style: AppTextStyles.caption(scheme.onSurfaceVariant),
                        ),
                        const SizedBox(width: 8),
                        Container(width: 7, height: 7, decoration: const BoxDecoration(color: AppColors.crimsonRed, shape: BoxShape.circle)),
                        const SizedBox(width: 4),
                        Text('Concepts', style: AppTextStyles.caption(scheme.onSurfaceVariant).copyWith(fontSize: 11)),
                        const SizedBox(width: 10),
                        Container(width: 7, height: 7, decoration: const BoxDecoration(color: Color(0xFFF59E0B), shape: BoxShape.circle)),
                        const SizedBox(width: 4),
                        Text('Domain Expansion', style: AppTextStyles.caption(const Color(0xFFD97706)).copyWith(fontSize: 11, fontWeight: FontWeight.w700)),
                      ],
                    ),
                  ],
                ),
              ),
              // PNG Download
              SizedBox(
                height: 38,
                child: NeuButton(
                  label: 'PNG',
                  icon: Icons.download_rounded,
                  isPrimary: false,
                  height: 38,
                  radius: 19,
                  onPressed: _isExporting ? null : () => _exportMindMapImage(format: 'png'),
                ),
              ),
              const SizedBox(width: 8),
              // JPG Download — Main Feature Highlighted
              SizedBox(
                height: 38,
                child: NeuButton(
                  label: 'Download JPG',
                  icon: Icons.image_rounded,
                  isPrimary: true,
                  height: 38,
                  radius: 19,
                  onPressed: _isExporting ? null : () => _exportMindMapImage(format: 'jpg'),
                ),
              ),
              const SizedBox(width: 8),
              // Share button
              NeuIconButton(
                icon: Icons.share_rounded,
                tooltip: 'Share Mind Map',
                onPressed: _isExporting
                    ? null
                    : () => _exportMindMapImage(format: 'png', isShare: true),
              ),
            ],
          ),
        ),

        // ── Interactive Aligned Canvas ───────────────────────────────────────
        Expanded(
          child: InteractiveViewer(
            minScale: 0.25,
            maxScale: 4.0,
            boundaryMargin: const EdgeInsets.all(400),
            child: Center(
              child: RepaintBoundary(
                key: _boundaryKey,
                child: Container(
                  width: 2200,
                  height: 1600,
                  color: isDark ? NeuColors.darkCanvas : NeuColors.lightCanvas,
                  child: CustomPaint(
                    painter: _HierarchicalMindMapPainter(
                      nodes: rawNodes,
                      isDark: isDark,
                      lectureTitle: lecture.title,
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ],
    );
  }
}

class _HierarchicalMindMapPainter extends CustomPainter {
  _HierarchicalMindMapPainter({
    required this.nodes,
    required this.isDark,
    required this.lectureTitle,
  });

  final List<MindMapNode> nodes;
  final bool isDark;
  final String lectureTitle;

  static const List<Color> _palette = [
    Color(0xFFE50914), // Crimson
    Color(0xFF2563EB), // Royal Blue
    Color(0xFF059669), // Emerald Green
    Color(0xFFD97706), // Amber
    Color(0xFF7C3AED), // Violet
    Color(0xFF0891B2), // Cyan
    Color(0xFFDB2777), // Pink
  ];

  @override
  void paint(Canvas canvas, Size size) {
    final center = Offset(size.width / 2, size.height / 2);

    // 1. Draw subtle blueprint dot grid
    final dotPaint = Paint()
      ..color = (isDark ? Colors.white : Colors.black).withValues(alpha: 0.05);
    for (double x = 35; x < size.width; x += 35) {
      for (double y = 35; y < size.height; y += 35) {
        canvas.drawCircle(Offset(x, y), 1.2, dotPaint);
      }
    }

    // 2. Identify root node
    final root = nodes.firstWhere(
      (n) =>
          n.id == 'root' ||
          n.id == 'center' ||
          n.parentId == null ||
          n.parentId!.isEmpty,
      orElse: () => MindMapNode(id: 'root', label: lectureTitle, tier: 0),
    );

    // 3. Identify Tier 1 pillars (direct children of root)
    final pillars = nodes.where((n) {
      if (n.id == root.id) return false;
      return n.parentId == root.id ||
          n.parentId == 'center' ||
          n.parentId == null ||
          n.tier == 1;
    }).toList();

    // Map each pillar ID to an assigned theme color
    final Map<String, Color> pillarColors = {};
    for (int i = 0; i < pillars.length; i++) {
      pillarColors[pillars[i].id] = _palette[i % _palette.length];
    }

    final Map<String, Offset> nodePositions = {root.id: center};
    const double pillarRadius = 360.0;

    // Group remaining nodes by pillar parent
    final Map<String, List<MindMapNode>> pillarChildren = {};
    for (final p in pillars) {
      pillarChildren[p.id] = [];
    }

    for (final n in nodes) {
      if (n.id == root.id || pillars.contains(n)) continue;
      if (n.parentId != null && pillarChildren.containsKey(n.parentId)) {
        pillarChildren[n.parentId]!.add(n);
      } else {
        // Balance across pillars
        String? targetPillar;
        int minCount = 9999;
        for (final p in pillars) {
          final count = pillarChildren[p.id]!.length;
          if (count < minCount) {
            minCount = count;
            targetPillar = p.id;
          }
        }
        if (targetPillar != null) {
          pillarChildren[targetPillar]!.add(n);
        }
      }
    }

    final int numPillars = math.max(1, pillars.length);
    final double sectorAngle = (2 * math.pi) / numPillars;

    // 4. Calculate collision-free aligned positions & draw connections
    for (int i = 0; i < numPillars; i++) {
      final p = pillars[i];
      final pAngle = sectorAngle * i - (math.pi / 2);
      final pPos = Offset(
        center.dx + pillarRadius * math.cos(pAngle),
        center.dy + pillarRadius * math.sin(pAngle),
      );
      nodePositions[p.id] = pPos;

      final pColor = pillarColors[p.id] ?? AppColors.crimsonRed;

      // Draw curved line from Root to Pillar
      final rootEdgePaint = Paint()
        ..color = pColor.withValues(alpha: isDark ? 0.7 : 0.5)
        ..strokeWidth = 3.5
        ..style = PaintingStyle.stroke
        ..strokeCap = StrokeCap.round;

      final rootPath = Path()
        ..moveTo(center.dx, center.dy)
        ..quadraticBezierTo(
          (center.dx + pPos.dx) / 2 + (math.cos(pAngle + math.pi / 2) * 20),
          (center.dy + pPos.dy) / 2 + (math.sin(pAngle + math.pi / 2) * 20),
          pPos.dx,
          pPos.dy,
        );
      canvas.drawPath(rootPath, rootEdgePaint);

      // Children strictly aligned within this pillar's angular sector
      final children = pillarChildren[p.id] ?? [];
      final int cCount = children.length;
      final double childSpread = sectorAngle * 0.76;

      for (int j = 0; j < cCount; j++) {
        final child = children[j];
        final childAngle = cCount == 1
            ? pAngle
            : (pAngle - childSpread / 2) + (childSpread / (cCount - 1)) * j;

        // Alternate radii across orbital rings (560 vs 740) so adjacent nodes never collide
        final double effectiveRadius =
            cCount <= 1 ? 620.0 : ((j % 2 == 0) ? 560.0 : 740.0);

        final childPos = Offset(
          center.dx + effectiveRadius * math.cos(childAngle),
          center.dy + effectiveRadius * math.sin(childAngle),
        );
        nodePositions[child.id] = childPos;

        // Draw curved connection from Pillar to Sub-concept
        final childEdgePaint = Paint()
          ..color = pColor.withValues(alpha: isDark ? 0.45 : 0.35)
          ..strokeWidth = 2.2
          ..style = PaintingStyle.stroke
          ..strokeCap = StrokeCap.round;

        final childPath = Path()
          ..moveTo(pPos.dx, pPos.dy)
          ..quadraticBezierTo(
            (pPos.dx + childPos.dx) / 2,
            (pPos.dy + childPos.dy) / 2,
            childPos.dx,
            childPos.dy,
          );
        canvas.drawPath(childPath, childEdgePaint);
      }
    }

    // 5. Draw leaf sub-nodes (Tier 2 and above)
    for (final p in pillars) {
      final pColor = pillarColors[p.id] ?? AppColors.crimsonRed;
      for (final child in (pillarChildren[p.id] ?? [])) {
        if (nodePositions.containsKey(child.id)) {
          final isExp = child.isExpansion ||
              (child.colorHex != null &&
                  child.colorHex!.toUpperCase().contains('F59E0B'));
          final childColor = isExp ? const Color(0xFFF59E0B) : pColor;
          _drawNode(
            canvas,
            nodePositions[child.id]!,
            child.label,
            tier: 2,
            accentColor: childColor,
            isExpansion: isExp,
          );
        }
      }
    }

    // 6. Draw Tier 1 Pillar nodes
    for (final p in pillars) {
      final isExp = p.isExpansion ||
          (p.colorHex != null &&
              p.colorHex!.toUpperCase().contains('F59E0B'));
      final pColor = isExp
          ? const Color(0xFFF59E0B)
          : (pillarColors[p.id] ?? AppColors.crimsonRed);
      _drawNode(
        canvas,
        nodePositions[p.id]!,
        p.label,
        tier: 1,
        accentColor: pColor,
        isExpansion: isExp,
      );
    }

    // 7. Draw Root node on top with glowing prominence
    _drawNode(
      canvas,
      center,
      root.label.isNotEmpty ? root.label : lectureTitle,
      tier: 0,
      accentColor: AppColors.crimsonRed,
    );
  }

  void _drawNode(
    Canvas canvas,
    Offset offset,
    String label, {
    required int tier,
    required Color accentColor,
    bool isExpansion = false,
  }) {
    final isRoot = tier == 0;
    final isPillar = tier == 1;

    final double fontSize = isRoot ? 14 : (isPillar ? 12 : 10.5);
    final FontWeight fontWeight =
        isRoot ? FontWeight.w800 : (isPillar ? FontWeight.w700 : FontWeight.w600);
    final double maxBoxWidth = isRoot ? 190 : (isPillar ? 150 : 135);
    final isUrdu = RegExp(r'[\u0600-\u06FF]').hasMatch(label);

    final textSpan = TextSpan(
      text: label,
      style: TextStyle(
        fontSize: fontSize,
        fontWeight: fontWeight,
        color: isRoot
            ? Colors.white
            : (isDark ? Colors.white : const Color(0xFF1E293B)),
      ),
    );

    final textPainter = TextPainter(
      text: textSpan,
      textDirection: isUrdu ? TextDirection.rtl : TextDirection.ltr,
      maxLines: 3,
      textAlign: TextAlign.center,
    )..layout(maxWidth: maxBoxWidth);

    final padH = isRoot ? 22.0 : (isPillar ? 16.0 : 12.0);
    final padV = isRoot ? 14.0 : (isPillar ? 10.0 : 8.0);

    final rect = Rect.fromCenter(
      center: offset,
      width: textPainter.width + padH * 2,
      height: textPainter.height + padV * 2,
    );
    final rrect = RRect.fromRectAndRadius(
      rect,
      Radius.circular(isRoot ? 18 : (isPillar ? 12 : 8)),
    );

    // Ambient drop shadow
    canvas.drawRRect(
      rrect.shift(const Offset(0, 4)),
      Paint()
        ..color = isRoot
            ? accentColor.withValues(alpha: 0.35)
            : (isExpansion
                ? const Color(0xFFF59E0B).withValues(alpha: 0.28)
                : Colors.black.withValues(alpha: isDark ? 0.3 : 0.08))
        ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 8),
    );

    // Node fill
    final fillPaint = Paint()
      ..color = isRoot
          ? accentColor
          : (isExpansion
              ? (isDark ? const Color(0xFF1E1E2E) : const Color(0xFFFFFBEB))
              : (isDark ? const Color(0xFF1E293B) : Colors.white));
    canvas.drawRRect(rrect, fillPaint);

    // Node outline border
    final borderPaint = Paint()
      ..color = isRoot
          ? AppColors.deepCrimson
          : (isExpansion
              ? const Color(0xFFF59E0B)
              : (isPillar
                  ? accentColor
                  : (isDark ? const Color(0xFF334155) : const Color(0xFFE2E8F0))))
      ..strokeWidth = isRoot ? 3.0 : (isExpansion ? 2.2 : (isPillar ? 2.0 : 1.2))
      ..style = PaintingStyle.stroke;
    canvas.drawRRect(rrect, borderPaint);

    // Accent indicator pip on pillars and expansion nodes
    if (isPillar || isExpansion) {
      final pipPaint = Paint()..color = accentColor;
      canvas.drawCircle(Offset(rect.left + 10, rect.top + 10), 3.5, pipPaint);
    }

    // Paint text centered
    textPainter.paint(
      canvas,
      Offset(
        offset.dx - textPainter.width / 2,
        offset.dy - textPainter.height / 2,
      ),
    );
  }

  @override
  bool shouldRepaint(covariant _HierarchicalMindMapPainter oldDelegate) => true;
}
